baseURL: "https://chaoray.github.io/"
languageCode: zh-tw
title: é«˜ä¸­ç­†è¨˜æ•´ç†
theme: "PaperModX"

defaultContentLanguage: zh-tw
defaultContentLanguageInSubdir: true

languages:
  zh-tw:
    languageName: "Traditional-Chinese"
    weight: 1
    profileMode:
      enabled: true
      title: ğŸ›è€ƒå‰ä¸€æ‹œï¼Œåˆ†æ•¸ä¸€ç™¾ğŸ›
      imageUrl: "img/four.gif"
      imageWidth: 150
      imageHeight: 150
      subtitle: ã€Œä½ å»å•åˆ¥äººå•¦ï¼Œæˆ‘ç„¡å¾·ç„¡èƒ½å¹«ä½ å®£æšæ–‡åŒ–ã€by å´´æ°‘å¤§ä½¬
      buttons:
        - name: åœ‹æ–‡
          url: posts/chinese
        - name: è‹±æ–‡
          url: posts/english
        - name: æ•¸å­¸
          url: posts/math
        - name: ç‰©ç†
          url: posts/physics
        - name: åœ°ç§‘
          url: posts/earth
        - name: æ­·å²
          url: posts/history
        - name: å…¬æ°‘
          url: posts/civics
    menu:
      main:
        - identifier: home
          name: ä¸»é 
          url: /
          weight: 1
        - identifier: post
          name: ç­†è¨˜
          url: posts
          weight: 2
        - identifier: search
          name: æœå°‹
          url: search
          weight: 4
        - identifier: fastuse
          name: å¿«é€Ÿä½¿ç”¨
          url: fastuse
          weight: 5
        - identifier: about
          name: é—œæ–¼
          url: about
          weight: 6
        - identifier: archives
          name: ç¸½è¦½
          url: archives
          weight: 7

outputs:
  home:
    - HTML
    - JSON

params:
  author: ["éƒ­å‡±æ˜", "å§œæ‰¿æ©", "è¶™æ–‡ç¿"]

  defaultTheme: light
  disableThemeToggle: false

  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCounts: true
  ShowLastMod: true
  VisitCount: true
  hideFooter: false
  TocSide: 'left'  # or 'right'
  TocOpen: true
  EnableInstantClick: true

  socialIcons:
    - name: github
      url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  label:
    text: "é«˜ä¸­ç­†è¨˜æ•´ç†"
    icon: "img/icon.webp"
    iconHeight: 35

  assets:
    favicon: "img/icon.webp"
    favicon16x16: "img/icon.webp"
    favicon32x32: "img/icon.webp"
    apple_touch_icon: "img/icon.webp"
    safari_pinned_tab: "img/icon.webp"

  taxonomies:
    category: categories
    tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
